name: OTACrawler-api EB Docker CI/CD

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t OTACrawler-api .

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Get timestamp
        id: timestamp
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: otacrawler-api
          environment_name: Otacrawlerapi-env
          version_label: OTACrawler-api-${{ steps.timestamp.outputs.date }}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: deploy.zip
